CREATE TABLE "ptest_0" (
	    "val_0" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_1" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_2" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_3" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_4" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_5" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_6" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_7" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_8" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_9" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_10" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_11" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_12" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_13" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_14" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_15" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_16" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_17" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_18" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_19" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_20" VARCHAR(500) DEFAULT 'Full Moon in the klink Shining, dont sleep Surveillance post my bail',
	    "val_21" VARCHAR(500) DEFAULT 'Armored cop open fire Glock On some kid who stepped so Fast was hard to grasp what even happened Til you seen that head blow Off his shoulders in slow-mo'
);
